nguage: python
python:
  - "2.7"
before_install:
 - "sudo apt-get update"
 - "sudo apt-get install python-dev libevent-dev"
# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: nosetests
